Description: RDS MSSQL Server with own security group

Resources:  
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SQL Server access
      VpcId: !ImportValue MyBase:VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1433
          ToPort: 1433
          CidrIp: 10.0.0.0/16
        - IpProtocol: tcp
          FromPort: 1433
          ToPort: 1433
          CidrIp: 0.0.0.0/0

  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "Subnets for RDS"
      SubnetIds:
        - !ImportValue MyBase:PublicSubnet1
        - !ImportValue MyBase:PublicSubnet2

  MSSQLServer:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: mydbinstance
      DBInstanceClass: db.t3.small
      AllocatedStorage: 200
      Engine: sqlserver-ex
      MasterUsername: sa
      MasterUserPassword: praktyka
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      LicenseModel: license-included
      MonitoringInterval: 0

Outputs:
  RDSEndpoint:
    Description: RDS instance endpoint to connect with SQL Server
    Value: !GetAtt MSSQLServer.Endpoint.Address
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", MSSQLServer] ]
    