Description: efs

Resources:
  FileSystemResource:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      FileSystemTags:
        - Key: Name
          Value: FileSystem

  MountTargetFirstSNet:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId: !ImportValue MyBase:PublicSubnet1
      SecurityGroups: 
        - !Ref ApplicationSecurityGroup 

  MountTargetSecondSNet:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId: !ImportValue MyBase:PublicSubnet2
      SecurityGroups: 
        - !Ref ApplicationSecurityGroup

  ApplicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http and ssh, efs and app specific api ports
      VpcId: !ImportValue MyBase:VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          CidrIp: 0.0.0.0/0 
      SecurityGroupEgress:
        - IpProtocol: -1 
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MyGroupName

Outputs: 
  EFSIP1:
    Description: "ip1"
    Value: !GetAtt MountTargetFirstSNet.IpAddress
  EFSIP2:
    Description: "ip2"
    Value: !GetAtt MountTargetSecondSNet.IpAddress

  EFSDNSName:
    Description: "EFS File System DNS Name"
    Value: !Sub "${FileSystemResource}.efs.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", EFS-DNS] ]
  SecurityGroupRef:
    Description: Reference to the SecurityGroup
    Value: !Ref ApplicationSecurityGroup
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", ApplicationSecurityGroup ] ]