AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance for Monitoring

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64'

Resources:
  MonitoringInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access from the Bastion Host
      VpcId: !ImportValue MyBase:VPC
      IamInstanceProfile: 
        Name : LabInstanceProfile
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9200
          ToPort: 9200
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5044
          ToPort: 5044
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5601
          ToPort: 5601
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MonitoringInstanceSG

  MonitoringInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.large
      ImageId: !Ref LatestAmiId
      KeyName: vockey
      IamInstanceProfile: LabInstanceProfile
      SubnetId: !ImportValue MyBase:PrivateSubnet1
      SecurityGroupIds:
        - !Ref MonitoringInstanceSG
      Tags:
        - Key: Name
          Value: MonitoringInstance
      UserData:
        Fn::Base64: !Sub 
        - |
          #!/bin/bash
          yum update -y
          yum install -y amazon-linux-extras
          yum install -y git
          yum install -y nfs-utils

          #EFS
          mkdir -p -m 777 /mnt/efs
          mount -t nfs4 ${EFS}:/ /mnt/efs
          chmod -R 777 mnt/

          yum install -y java-11-amazon-corretto
          rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

          tee /etc/yum.repos.d/elasticsearch.repo <<EOF
          [elasticsearch]
          name=Elasticsearch repository
          baseurl=https://artifacts.elastic.co/packages/8.x/yum
          gpgcheck=1
          gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
          enabled=1
          autorefresh=1
          type=rpm-md
          EOF

          yum install elasticsearch -y
          sed -i 's/#network.host: 192.168.0.1/network.host: 0.0.0.0/' /etc/elasticsearch/elasticsearch.yml
          sed -i 's/#discovery.seed_hosts:.*/discovery.seed_hosts: []/' /etc/elasticsearch/elasticsearch.yml
          sed -i 's/xpack.security.enabled: true/xpack.security.enabled: false/' /etc/elasticsearch/elasticsearch.yml
          systemctl enable elasticsearch
          systemctl start elasticsearch

          yum install logstash -y
          cat > /etc/logstash/conf.d/logstash.conf <<EOF
          input {
            beats {
              port => 5044
            }
          }
          output {
            if [@metadata][pipeline] {
              elasticsearch {
                hosts           => ["localhost:9200"]
                manage_template => false
                index           => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
                pipeline        => "%{[@metadata][pipeline]}"
              }
            } else {
              elasticsearch {
                hosts           => ["localhost:9200"]
                manage_template => false
                index           => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
              }
            }
          }
          EOF
          systemctl enable logstash
          systemctl start logstash
          
          yum install kibana -y
          sed -i 's/#server.port: 5601/server.port: 5601/' /etc/kibana/kibana.yml
          sed -i 's/#server.host: "localhost"/server.host: "0.0.0.0"/' /etc/kibana/kibana.yml
          sed -i 's|#elasticsearch.hosts:.*|elasticsearch.hosts: ["http://localhost:9200"]|' /etc/kibana/kibana.yml
          systemctl enable kibana
          systemctl start kibana
          
          yum install filebeat -y
          sed -i 's/  enabled: false/  enabled: true/' /etc/filebeat/filebeat.yml
          sed -i '32s|.*|    - mnt/efs/*.log|' /etc/filebeat/filebeat.yml
          sed -i 's|output.elasticsearch:|#output.elasticsearch:|' /etc/filebeat/filebeat.yml
          sed -i 's|  hosts:.*|  #hosts: ["localhost:9200"]|' /etc/filebeat/filebeat.yml
          sed -i 's|#output.logstash:|output.logstash:|' /etc/filebeat/filebeat.yml
          sed -i '158s|.*|  hosts: ["localhost:5044"]|' /etc/filebeat/filebeat.yml

          filebeat modules enable system
          sed -i 's/  enabled: false/  enabled: true/' /etc/filebeat/modules.d/system.yml
          filebeat setup --pipelines --modules system
          filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["0.0.0.0:9200"]'
          filebeat setup -E output.logstash.enabled=false -E output.elasticsearch.hosts=['localhost:9200'] -E setup.kibana.host=localhost:5601
          systemctl start filebeat
          systemctl enable filebeat
          

        - EFS: !ImportValue EFS:EFS-DNS

Outputs:
  PMonitoringInstancePublicIP:
    Description: "Private IP of the Monitoring Instance"
    Value: !GetAtt MonitoringInstance.PrivateIp
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", "MonitoringInstancePrivateIP" ] ]

