- name: Deploy CloudShirt app to GKE
  hosts: localhost
  vars:
    project_id: "{{ project_id }}"
    cluster_name: "{{ cluster_name }}"
    region: "{{ region }}"
  tasks:
    - name: Authenticate kubectl with GKE cluster
      ansible.builtin.shell: |
        gcloud container clusters get-credentials {{ cluster_name }} --region {{ region }} --project {{ project_id }}
      environment:
        CLOUDSDK_CORE_PROJECT: "{{ project_id }}"

    - name: Apply CloudShirt + SQL Kubernetes deployments and services
      kubernetes.core.k8s:
        state: present
        namespace: default
        definition: "{{ lookup('file', 'k8s/cloudshirt-deployment.yaml') }}"