apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudshirt-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudshirt
  template:
    metadata:
      labels:
        app: cloudshirt
    spec:
      containers:
      - name: cloudshirt
        image: europe-west1-docker.pkg.dev/notional-radio-450521-a4/my-app-repo/eshopwebmvc:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Docker"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudshirt-service
spec:
  type: LoadBalancer
  selector:
    app: cloudshirt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80