apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudshirt-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudshirt
  template:
    metadata:
      labels:
        app: cloudshirt
    spec:
      containers:
      - name: cloudshirt
        image: europe-west1-docker.pkg.dev/notional-radio-450521-a4/my-app-repo/eshopwebmvc:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Docker"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver-service;User=sa;Password=praktyka;Database=Microsoft.eShopOnWebDb"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/azure-sql-edge
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "praktyka"
        - name: ACCEPT_EULA
          value: "Y"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudshirt-service
spec:
  type: LoadBalancer
  selector:
    app: cloudshirt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 2137
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
